
[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify \
  """

[build.environment]
HUGO_VERSION = "0.121.0"
DART_SASS_VERSION = "1.70.0"
TZ = "America/Los_Angeles"


# Site ID Configuration
[build]
  command = "netlify deploy"
  functions = "netlify/functions/"
  site = "7c670c65-ad59-41cc-b098-3159738f0049"